# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab1c4856cf1ee70ff043af9dd96783e7f3d73b278d03143cbd2fa5067457d49f5ec3685d20b96e4174a1b679e369c6b4711117fa16016eb46c07ccd9749f320b

test:
  secret_key_base: 0dd5a46c52bb30af788f37ffdbb524b0651c347c0b48506845e671f909ff601de83645a291be24804cc251f5c41635c15423e380d6d649ff7cead015032db674

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
